"""empty message

Revision ID: 1620c958de96
Revises: 
Create Date: 2023-04-13 19:03:21.530641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1620c958de96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    # ### end Alembic commands ###
