"""empty message

Revision ID: 2603212e3c96
Revises: 2b808da8258b
Create Date: 2023-06-14 14:19:51.108764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2603212e3c96'
down_revision = '2b808da8258b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('children')
    op.drop_table('parents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('parents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('children',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name='children_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='children_pkey')
    )
    # ### end Alembic commands ###
