"""empty message

Revision ID: 4e38526bfe59
Revises: b1930dacc0b1
Create Date: 2023-07-08 18:57:24.759596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e38526bfe59'
down_revision = 'b1930dacc0b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
