"""empty message

Revision ID: 76739333bb5f
Revises: baf8d2b042e3
Create Date: 2023-05-20 19:18:57.611745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76739333bb5f'
down_revision = 'baf8d2b042e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
