"""empty message

Revision ID: 9548b7f37d9d
Revises: 4e38526bfe59
Create Date: 2023-07-08 19:19:12.804814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9548b7f37d9d'
down_revision = '4e38526bfe59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
