"""empty message

Revision ID: 99638937b904
Revises: 76739333bb5f
Create Date: 2023-05-20 19:21:23.588022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99638937b904'
down_revision = '76739333bb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
