"""empty message

Revision ID: a07a820469f8
Revises: 99638937b904
Create Date: 2023-05-20 21:44:10.744834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07a820469f8'
down_revision = '99638937b904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_fields', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'template_fields', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_fields', type_='foreignkey')
    op.drop_column('template_fields', 'template_id')
    # ### end Alembic commands ###
