"""empty message

Revision ID: b252c9efd740
Revises: 44280b7e7a22
Create Date: 2023-05-20 14:13:49.455859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b252c9efd740'
down_revision = '44280b7e7a22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_fields', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_fields', 'data')
    # ### end Alembic commands ###
