"""empty message

Revision ID: cef4f5de8cb8
Revises: 9548b7f37d9d
Create Date: 2023-07-08 19:27:54.267499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef4f5de8cb8'
down_revision = '9548b7f37d9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
