"""empty message

Revision ID: dc6ea5b1d60e
Revises: cb1a6685fb62
Create Date: 2023-05-22 23:22:18.222938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6ea5b1d60e'
down_revision = 'cb1a6685fb62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_field_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('template_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_field_id'], ['template_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_field_answers')
    # ### end Alembic commands ###
