"""empty message

Revision ID: ff0e824b5f6f
Revises: dc6ea5b1d60e
Create Date: 2023-05-23 20:12:14.931770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0e824b5f6f'
down_revision = 'dc6ea5b1d60e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
